services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: maconly
      POSTGRES_PASSWORD: maconly
      POSTGRES_DB: maconly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maconly -d maconly_db"]
      interval: 3s
      timeout: 3s
      retries: 10

  backend:
    build: .
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    # volumes:
    #   - .:/code
    working_dir: /code
    environment:
      - DATABASE_URL=postgresql+psycopg2://maconly:maconly@db:5432/maconly_db
      - PYTHONPATH=/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  backend2:
    build: .
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    working_dir: /code
    environment:
      - DATABASE_URL=postgresql+psycopg2://maconly:maconly@db:5432/maconly_db
      - PYTHONPATH=/code
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
